export type {
  Attribute,
  Binding,
  BindingId,
  BindingKind,
  BindingReference,
  BoundAttribute,
  BoundStyle,
  ClassAttribute,
  ClassItem,
  DynamicClass,
  ElementNode,
  Expression,
  ForNode,
  FragmentNode,
  GlobalReference,
  IfBranch,
  IfNode,
  InterpolationNode,
  Prop,
  PropsParameter,
  Reference,
  RenderNode,
  Span,
  SpreadAttribute,
  SpreadKey,
  StaticAttribute,
  StaticClass,
  StaticStyle,
  StyleAttribute,
  StyleDeclaration,
  TextNode,
  ToggleClass,
  TypeDeclaration,
  TypeText,
  UfComponent,
  UfExport,
  UfModule,
} from "./types.ts";
export { IR_VERSION } from "./version.ts";
export {
  bindingId,
  createBinding,
  createBindingReference,
  createBoundAttribute,
  createBoundStyle,
  createBranch,
  createClassAttribute,
  createComponent,
  createDynamicClass,
  createElement,
  createExport,
  createExpression,
  createFor,
  createFragment,
  createGlobalReference,
  createIf,
  createInterpolation,
  createModule,
  createProp,
  createPropsParameter,
  createSpreadAttribute,
  createSpreadKey,
  createStaticAttribute,
  createStaticClass,
  createStaticStyle,
  createStyleAttribute,
  createText,
  createToggleClass,
  createTypeDeclaration,
  createTypeText,
  span,
} from "./builders.ts";
export {
  ATTRIBUTE_KINDS,
  BINDING_KINDS,
  childrenOf,
  collectFeatures,
  expressionsOf,
  RENDER_NODE_KINDS,
  spansOf,
  walk,
} from "./visit.ts";
export type {
  LocatedExpression,
  LocatedSpan,
  ModuleFeatures,
  VisitedNode,
  Visitor,
} from "./visit.ts";
export { irSchema } from "./schema.ts";
export type { JsonSchema } from "./schema.ts";
export { validateModule } from "./validate.ts";
export type { IrValidationError } from "./validate.ts";
export { checkInvariants } from "./invariants.ts";
export {
  ALLOWED_GLOBALS,
  isComponentName,
  isExportName,
  isIdentifier,
  PROP_NAME_PATTERN,
  RESERVED_PROP_NAMES,
  reservedPropName,
} from "./names.ts";
export { listBoxSize } from "./listbox.ts";
export {
  CHILDLESS_ATTRIBUTES,
  FIXED_VALUE_INPUT_TYPES,
  isDroppedEmptyUrl,
  isStateAttribute,
  isWhitespaceText,
  LEADING_LINE_FEED_ELEMENTS,
  STATE_ATTRIBUTES,
  TEMPLATE_SYNTAX_ATTRIBUTES,
  UNBINDABLE_ATTRIBUTES,
  unbindableAttribute,
  UNINTERPOLATED_ELEMENTS,
  UNPORTABLE_ELEMENTS,
  UNRENDERED_ATTRIBUTES,
  WHITESPACE_DROPPING_ELEMENTS,
} from "./portability.ts";
export {
  ARIA_ATTRIBUTES,
  BINDABLE_BOOLEAN_ATTRIBUTES,
  BLOCK_ELEMENTS,
  BOOLEAN_ATTRIBUTES,
  canonicalNumber,
  DOCUMENT_ATTRIBUTES,
  ELEMENT_ATTRIBUTES,
  GENERATED_ID_PREFIX,
  GLOBAL_ATTRIBUTES,
  HEADING_ELEMENTS,
  HTML_ELEMENTS,
  ID_REFERENCE_ATTRIBUTES,
  idReferencesIn,
  isBlockElement,
  isBooleanAttribute,
  isDataAttribute,
  isHtmlAttribute,
  isHtmlElement,
  isJavaScriptUrl,
  isNumberTypedAttribute,
  isVoidElement,
  NESTED_DOCUMENT_ATTRIBUTES,
  NUMBER_TYPED_ATTRIBUTES,
  NUMBER_TYPED_GLOBAL_ATTRIBUTES,
  NUMERIC_ATTRIBUTES,
  OBSOLETE_ELEMENTS,
  P_CLOSING_ELEMENTS,
  PERMITTED_CHILDREN,
  REPAIRED_DESCENDANTS,
  replaceIdReferences,
  REQUIRED_PARENTS,
  TEXT_ONLY_ELEMENTS,
  TEXTLESS_ELEMENTS,
  TRUE_VALUED_ATTRIBUTES,
  unanalysableUrl,
  unkeptCharacter,
  UNRENDERABLE_ELEMENTS,
  URL_ATTRIBUTES,
  VOID_ELEMENTS,
  WHITESPACE_PRESERVING_ELEMENTS,
} from "./html.ts";
export type { NumberKind, UnkeptCharacter } from "./html.ts";
export {
  elementNamespace,
  isSvgAttribute,
  isSvgElement,
  SVG_ELEMENT_ATTRIBUTES,
  SVG_ELEMENTS,
  SVG_GLOBAL_ATTRIBUTES,
  SVG_HTML_INTEGRATION_POINTS,
  SVG_PRESENTATION_ATTRIBUTES,
  SVG_TEXT_ELEMENTS,
  SVG_UNRENDERABLE_ELEMENTS,
  SVG_WHITESPACE_KEEPING_ELEMENT,
} from "./svg.ts";
export type { Namespace } from "./svg.ts";
export {
  CSS_SHORTHANDS,
  cssPropertiesOverlap,
  cssValueProblem,
  isCssPropertyName,
  isCustomProperty,
  UNITLESS_PROPERTIES,
} from "./css.ts";
