export type {
  ApiEvent,
  ApiEventParameter,
  ApiMember,
  ApiReference,
  ApiSlot,
  Attribute,
  Binding,
  BindingId,
  BindingKind,
  BindingReference,
  BoundAttribute,
  BoundStyle,
  ClassAttribute,
  ClassItem,
  Code,
  CodeReference,
  ComponentApi,
  ComponentAttribute,
  ComponentCandidate,
  ComponentNode,
  ConstItem,
  DerivedItem,
  DynamicCandidate,
  DynamicClass,
  DynamicNode,
  ElementNode,
  EmitReference,
  Emits,
  EventAttribute,
  EventControl,
  EventDeclaration,
  EventParameter,
  EventReference,
  Exposes,
  Expression,
  ForNode,
  FragmentNode,
  FunctionCode,
  FunctionHandler,
  FunctionItem,
  GetterSource,
  GlobalReference,
  Handler,
  IdItem,
  IfBranch,
  IfNode,
  ImportedName,
  InjectionKeyDeclaration,
  InjectItem,
  InlineHandler,
  InterpolationNode,
  KeyApi,
  LifecycleItem,
  ListenerAttribute,
  ModelAttribute,
  ModelBindingAttribute,
  ModelItem,
  ModuleApi,
  ModuleImport,
  NarrowedPath,
  Parameter,
  ParameterPattern,
  Prop,
  PropAttribute,
  PropsParameter,
  ProvideItem,
  RefAttribute,
  Reference,
  RefSource,
  RenderNode,
  SetupItem,
  SlotDeclaration,
  SlotFill,
  SlotOutletNode,
  SlotReference,
  Slots,
  Span,
  SpreadAttribute,
  SpreadKey,
  StateItem,
  StaticAttribute,
  StaticClass,
  StaticStyle,
  StyleAttribute,
  StyleDeclaration,
  TagCandidate,
  TemplateRefItem,
  TextNode,
  ToggleClass,
  TypeDeclaration,
  TypeText,
  UfComponent,
  UfExport,
  UfModule,
  VariableItem,
  WatchEffectItem,
  WatchItem,
  WatchSource,
  WriteReference,
} from "./types.ts";
export { IR_VERSION } from "./version.ts";
export {
  bindingId,
  createApiReference,
  createBinding,
  createBindingReference,
  createBoundAttribute,
  createBoundStyle,
  createBranch,
  createClassAttribute,
  createCode,
  createComponent,
  createComponentNode,
  createConstItem,
  createDerivedItem,
  createDynamicClass,
  createDynamicNode,
  createElement,
  createEmitReference,
  createEmits,
  createEventAttribute,
  createEventControl,
  createEventDeclaration,
  createEventParameter,
  createEventReference,
  createExport,
  createExposes,
  createExpression,
  createFor,
  createFragment,
  createFunctionCode,
  createFunctionHandler,
  createFunctionItem,
  createGetterSource,
  createGlobalReference,
  createIdItem,
  createIf,
  createImportedName,
  createInjectionKeyDeclaration,
  createInjectItem,
  createInlineHandler,
  createInterpolation,
  createLifecycleItem,
  createListenerAttribute,
  createModelAttribute,
  createModelBindingAttribute,
  createModelItem,
  createModule,
  createModuleImport,
  createNarrowedPath,
  createParameter,
  createParameterPattern,
  createProp,
  createPropAttribute,
  createPropsParameter,
  createProvideItem,
  createRefAttribute,
  createRefSource,
  createSlotDeclaration,
  createSlotFill,
  createSlotOutlet,
  createSlotReference,
  createSlots,
  createSpreadAttribute,
  createSpreadKey,
  createStateItem,
  createStaticAttribute,
  createStaticClass,
  createStaticStyle,
  createStyleAttribute,
  createTemplateRefItem,
  createText,
  createToggleClass,
  createTypeDeclaration,
  createTypeText,
  createVariableItem,
  createWatchEffectItem,
  createWatchItem,
  createWriteReference,
  span,
} from "./builders.ts";
export type {
  ComponentOptions,
  FunctionOptions,
  ListenerOptions,
  ModelModifiers,
  ModelOptions,
  ParameterOptions,
  SlotFillOptions,
  WatchOptions,
} from "./builders.ts";
export {
  ATTRIBUTE_KINDS,
  BINDING_KINDS,
  childrenOf,
  CODE_REFERENCE_KINDS,
  codeOf,
  collectFeatures,
  expressionsOf,
  functionsOf,
  HANDLER_KINDS,
  RENDER_NODE_KINDS,
  SETUP_ITEM_KINDS,
  spansOf,
  walk,
  WATCH_SOURCE_KINDS,
} from "./visit.ts";
export type {
  CodeContext,
  FunctionRole,
  LocatedCode,
  LocatedExpression,
  LocatedFunction,
  LocatedSpan,
  ModuleFeatures,
  VisitedNode,
  Visitor,
} from "./visit.ts";
export { impurity, summarize, summarizeCode, summarizeTracked } from "./summary.ts";
export type { CodeSummary, FunctionSummary } from "./summary.ts";
export { irSchema } from "./schema.ts";
export type { JsonSchema } from "./schema.ts";
export { validateModule } from "./validate.ts";
export type { IrValidationError } from "./validate.ts";
export { checkInvariants, isMemberPath } from "./invariants.ts";
export {
  ALLOWED_GLOBALS,
  ANGULAR_KEYWORDS,
  BROWSER_GLOBALS,
  CLIENT_GLOBALS,
  isComponentName,
  isExportName,
  isIdentifier,
  PROP_NAME_PATTERN,
  PURE_GLOBALS,
  readsDom,
  RESERVED_PROP_NAMES,
  RESERVED_TYPE_NAMES,
  reservedEventName,
  reservedParameterName,
  reservedPropName,
  reservedPropsParameterName,
  reservedSetupName,
  SCHEDULING_GLOBALS,
} from "./names.ts";
export { LIB_DOM_GLOBALS, WINDOW_MEMBER_GLOBALS } from "./browser.ts";
export {
  DOM_EVENTS,
  EVENT_INTERFACES,
  EVENT_METHODS,
  extendsEventInterface,
  PASSIVE_EVENTS,
  PORTABLE_EVENT_INTERFACES,
  PORTABLE_EVENT_MEMBERS,
  UNSUPPORTED_EVENTS,
  WINDOW_EVENTS,
} from "./events.ts";
export { listBoxSize } from "./listbox.ts";
export {
  angularRespellsRegex,
  CHILDLESS_ATTRIBUTES,
  CONTEXTUAL_ROOT_ELEMENTS,
  DRAFT_ARIA_ATTRIBUTES,
  FIXED_VALUE_INPUT_TYPES,
  isDroppedEmptyUrl,
  isStateAttribute,
  isWhitespaceText,
  LEADING_LINE_FEED_ELEMENTS,
  NULLISH_VALUE_ELEMENTS,
  RAW_TEXT_ELEMENTS,
  STATE_ATTRIBUTES,
  TEMPLATE_SYNTAX_ATTRIBUTES,
  UNBINDABLE_ATTRIBUTES,
  unbindableAttribute,
  UNDECLARED_ATTRIBUTES,
  undeclaredAttribute,
  undeclaredBy,
  UNINTERPOLATED_ELEMENTS,
  UNPORTABLE_ELEMENTS,
  UNRENDERED_ATTRIBUTES,
  WHITESPACE_DROPPING_ELEMENTS,
} from "./portability.ts";
export type { TypedFramework } from "./portability.ts";
export {
  ARIA_ATTRIBUTES,
  BINDABLE_BOOLEAN_ATTRIBUTES,
  BLOCK_ELEMENTS,
  BOOLEAN_ATTRIBUTES,
  canonicalNumber,
  DOCUMENT_ATTRIBUTES,
  ELEMENT_ATTRIBUTES,
  GENERATED_ID_PREFIX,
  GLOBAL_ATTRIBUTES,
  HEADING_ELEMENTS,
  HTML_ELEMENTS,
  ID_REFERENCE_ATTRIBUTES,
  idReferencesIn,
  isBlockElement,
  isBooleanAttribute,
  isDataAttribute,
  isHtmlAttribute,
  isHtmlElement,
  isJavaScriptUrl,
  isNumberTypedAttribute,
  isVoidElement,
  NESTED_DOCUMENT_ATTRIBUTES,
  NUMBER_TYPED_ATTRIBUTES,
  NUMBER_TYPED_GLOBAL_ATTRIBUTES,
  NUMERIC_ATTRIBUTES,
  OBSOLETE_ELEMENTS,
  P_CLOSING_ELEMENTS,
  PERMITTED_CHILDREN,
  REPAIRED_DESCENDANTS,
  replaceIdReferences,
  REQUIRED_PARENTS,
  TEXT_ONLY_ELEMENTS,
  TEXTLESS_ELEMENTS,
  TRUE_VALUED_ATTRIBUTES,
  unanalysableUrl,
  unkeptCharacter,
  UNRENDERABLE_ELEMENTS,
  URL_ATTRIBUTES,
  VOID_ELEMENTS,
  WHITESPACE_PRESERVING_ELEMENTS,
} from "./html.ts";
export type { NumberKind, UnkeptCharacter } from "./html.ts";
export {
  elementNamespace,
  isSvgAttribute,
  isSvgElement,
  SVG_ELEMENT_ATTRIBUTES,
  SVG_ELEMENTS,
  SVG_GLOBAL_ATTRIBUTES,
  SVG_HTML_INTEGRATION_POINTS,
  SVG_PRESENTATION_ATTRIBUTES,
  SVG_TEXT_ELEMENTS,
  SVG_UNRENDERABLE_ELEMENTS,
  SVG_WHITESPACE_KEEPING_ELEMENT,
} from "./svg.ts";
export type { Namespace } from "./svg.ts";
export {
  angularLowercases,
  angularMisreads,
  CSS_PROPERTIES,
  CSS_SHORTHANDS,
  cssPropertiesOverlap,
  cssValueProblem,
  isCssPropertyName,
  isCustomProperty,
  isKnownCssProperty,
  UNITLESS_PROPERTIES,
} from "./css.ts";
