// The components `behaviourModules` (./behaviour-modules.ts) serves to the browser project, one
// loader per source of ./behaviour-sources.ts. That plugin replaces this module with the real
// loaders; without it, importing this module fails.
import type { Component } from "vue";

export const components: Readonly<Record<string, () => Promise<{ default: Component }>>> =
  notServed();

function notServed(): never {
  throw new Error(
    "behaviour-manifest.ts is generated by behaviourModules: run this test in the browser project of vitest.config.ts.",
  );
}
