// The DOM interface of each element (ADR-0049), as the authoring types' `DomElementFor` reads
// lib.dom: `HTMLElementTagNameMap` first, then `SVGElementTagNameMap`, else `Element`. It is what
// an untyped template ref holds, and what React's `ref` on the element takes: @types/react's
// elements are one flat map too, so an SVG `<title>` is an `HTMLTitleElement` in both.
// test/toolchain.test.ts checks the tables against lib.dom and @types/react with tsgo (L4).

/** The HTML elements whose interface is `HTMLElement`. */
const PLAIN_ELEMENTS: ReadonlySet<string> = new Set([
  "abbr",
  "address",
  "article",
  "aside",
  "b",
  "bdi",
  "bdo",
  "cite",
  "code",
  "dd",
  "dfn",
  "dt",
  "em",
  "figcaption",
  "figure",
  "footer",
  "header",
  "hgroup",
  "i",
  "kbd",
  "main",
  "mark",
  "nav",
  "noscript",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "search",
  "section",
  "small",
  "strong",
  "sub",
  "summary",
  "sup",
  "u",
  "var",
  "wbr",
]);

/** The other HTML elements, each with its interface. */
const HTML_INTERFACES: ReadonlyMap<string, string> = new Map(
  Object.entries({
    a: "HTMLAnchorElement",
    area: "HTMLAreaElement",
    audio: "HTMLAudioElement",
    base: "HTMLBaseElement",
    blockquote: "HTMLQuoteElement",
    body: "HTMLBodyElement",
    br: "HTMLBRElement",
    button: "HTMLButtonElement",
    canvas: "HTMLCanvasElement",
    caption: "HTMLTableCaptionElement",
    col: "HTMLTableColElement",
    colgroup: "HTMLTableColElement",
    data: "HTMLDataElement",
    datalist: "HTMLDataListElement",
    del: "HTMLModElement",
    details: "HTMLDetailsElement",
    dialog: "HTMLDialogElement",
    div: "HTMLDivElement",
    dl: "HTMLDListElement",
    embed: "HTMLEmbedElement",
    fieldset: "HTMLFieldSetElement",
    form: "HTMLFormElement",
    h1: "HTMLHeadingElement",
    h2: "HTMLHeadingElement",
    h3: "HTMLHeadingElement",
    h4: "HTMLHeadingElement",
    h5: "HTMLHeadingElement",
    h6: "HTMLHeadingElement",
    head: "HTMLHeadElement",
    hr: "HTMLHRElement",
    html: "HTMLHtmlElement",
    iframe: "HTMLIFrameElement",
    img: "HTMLImageElement",
    input: "HTMLInputElement",
    ins: "HTMLModElement",
    label: "HTMLLabelElement",
    legend: "HTMLLegendElement",
    li: "HTMLLIElement",
    link: "HTMLLinkElement",
    map: "HTMLMapElement",
    menu: "HTMLMenuElement",
    meta: "HTMLMetaElement",
    meter: "HTMLMeterElement",
    object: "HTMLObjectElement",
    ol: "HTMLOListElement",
    optgroup: "HTMLOptGroupElement",
    option: "HTMLOptionElement",
    output: "HTMLOutputElement",
    p: "HTMLParagraphElement",
    picture: "HTMLPictureElement",
    pre: "HTMLPreElement",
    progress: "HTMLProgressElement",
    q: "HTMLQuoteElement",
    script: "HTMLScriptElement",
    select: "HTMLSelectElement",
    slot: "HTMLSlotElement",
    source: "HTMLSourceElement",
    span: "HTMLSpanElement",
    style: "HTMLStyleElement",
    table: "HTMLTableElement",
    tbody: "HTMLTableSectionElement",
    td: "HTMLTableCellElement",
    template: "HTMLTemplateElement",
    textarea: "HTMLTextAreaElement",
    tfoot: "HTMLTableSectionElement",
    th: "HTMLTableCellElement",
    thead: "HTMLTableSectionElement",
    time: "HTMLTimeElement",
    title: "HTMLTitleElement",
    tr: "HTMLTableRowElement",
    track: "HTMLTrackElement",
    ul: "HTMLUListElement",
    video: "HTMLVideoElement",
  }),
);

/** The SVG elements HTML does not name too, each with its interface. */
const SVG_INTERFACES: ReadonlyMap<string, string> = new Map(
  Object.entries({
    animate: "SVGAnimateElement",
    animateMotion: "SVGAnimateMotionElement",
    animateTransform: "SVGAnimateTransformElement",
    circle: "SVGCircleElement",
    clipPath: "SVGClipPathElement",
    defs: "SVGDefsElement",
    desc: "SVGDescElement",
    ellipse: "SVGEllipseElement",
    feBlend: "SVGFEBlendElement",
    feColorMatrix: "SVGFEColorMatrixElement",
    feComponentTransfer: "SVGFEComponentTransferElement",
    feComposite: "SVGFECompositeElement",
    feConvolveMatrix: "SVGFEConvolveMatrixElement",
    feDiffuseLighting: "SVGFEDiffuseLightingElement",
    feDisplacementMap: "SVGFEDisplacementMapElement",
    feDistantLight: "SVGFEDistantLightElement",
    feDropShadow: "SVGFEDropShadowElement",
    feFlood: "SVGFEFloodElement",
    feFuncA: "SVGFEFuncAElement",
    feFuncB: "SVGFEFuncBElement",
    feFuncG: "SVGFEFuncGElement",
    feFuncR: "SVGFEFuncRElement",
    feGaussianBlur: "SVGFEGaussianBlurElement",
    feImage: "SVGFEImageElement",
    feMerge: "SVGFEMergeElement",
    feMergeNode: "SVGFEMergeNodeElement",
    feMorphology: "SVGFEMorphologyElement",
    feOffset: "SVGFEOffsetElement",
    fePointLight: "SVGFEPointLightElement",
    feSpecularLighting: "SVGFESpecularLightingElement",
    feSpotLight: "SVGFESpotLightElement",
    feTile: "SVGFETileElement",
    feTurbulence: "SVGFETurbulenceElement",
    filter: "SVGFilterElement",
    foreignObject: "SVGForeignObjectElement",
    g: "SVGGElement",
    image: "SVGImageElement",
    line: "SVGLineElement",
    linearGradient: "SVGLinearGradientElement",
    marker: "SVGMarkerElement",
    mask: "SVGMaskElement",
    metadata: "SVGMetadataElement",
    mpath: "SVGMPathElement",
    path: "SVGPathElement",
    pattern: "SVGPatternElement",
    polygon: "SVGPolygonElement",
    polyline: "SVGPolylineElement",
    radialGradient: "SVGRadialGradientElement",
    rect: "SVGRectElement",
    set: "SVGSetElement",
    stop: "SVGStopElement",
    svg: "SVGSVGElement",
    switch: "SVGSwitchElement",
    symbol: "SVGSymbolElement",
    text: "SVGTextElement",
    textPath: "SVGTextPathElement",
    tspan: "SVGTSpanElement",
    use: "SVGUseElement",
    view: "SVGViewElement",
  }),
);

/** The DOM interface of an element: `HTMLInputElement`, `SVGCircleElement`, `HTMLElement`. */
export function elementInterface(tag: string): string {
  if (PLAIN_ELEMENTS.has(tag)) return "HTMLElement";
  return HTML_INTERFACES.get(tag) ?? SVG_INTERFACES.get(tag) ?? "Element";
}
