import type { DiagnosticCode, Severity } from "./types.ts";

/** The documentation of one diagnostic code. */
export interface CatalogueEntry {
  code: DiagnosticCode;
  /** A stable kebab-case name, for configuration and search. */
  name: string;
  /** The default severity. */
  severity: Severity;
  /** One line, shown in listings. */
  title: string;
  /** Markdown: what the diagnostic means and how to resolve it. */
  description: string;
}

/** The bands that group codes (plan §5.9). */
export const BANDS: Readonly<Record<string, string>> = {
  UF1: "Syntax and components",
  UF2: "Setup and macros",
  UF3: "JSX and cross-component usage",
  UF4: "Portability (capabilities)",
  UF5: "Styles",
  UF6: "Types",
  UF7: "Config and tooling",
  UF8: "Plugins",
  UF9: "Internal",
};

const entries: CatalogueEntry[] = [
  {
    code: "UF1001",
    name: "syntax-error",
    severity: "error",
    title: "The file is not valid TSX",
    description: [
      "The parser could not read the file as TSX. The message names the first problem it met.",
      "",
      "Fix the syntax error. Any TypeScript editor shows the same error, because a `.uf.tsx` file",
      "is ordinary TSX.",
      "",
      "A raw `}` or `>` in JSX text is a syntax error: write `&#x7D;` or `&gt;`, which every JSX",
      "implementation decodes (none decodes `&rbrace;`, and `{'}'}` is an expression). The fix",
      "does so where the file then parses. Where it would not, the `}` is more likely code after",
      "an element that is not closed.",
    ].join("\n"),
  },
  {
    code: "UF1002",
    name: "unsupported-syntax",
    severity: "error",
    title: "The compiler cannot lower this construct yet",
    description: [
      "The construct is part of the source language, but this version of the compiler cannot",
      "lower it to every target yet. The compiler never copies code it has not analysed into an",
      "output, so it reports the construct instead.",
      "",
      "Rewrite the code without the construct, or wait for the release that supports it. The",
      "message names the construct.",
    ].join("\n"),
  },
  {
    code: "UF1101",
    name: "no-component",
    severity: "error",
    title: "The file exports no component",
    description: [
      "A `.uf.tsx` file holds components: exported PascalCase functions whose last statement",
      "returns JSX.",
      "",
      "```tsx",
      "export default function Greeting() {",
      "  return <p>Hello, world!</p>;",
      "}",
      "```",
      "",
      "Export a component, or move framework-agnostic code to a plain `.ts` module.",
    ].join("\n"),
  },
  {
    code: "UF1102",
    name: "invalid-component",
    severity: "error",
    title: "A component must be a named PascalCase function that returns JSX",
    description: [
      "A component is a function whose body is its setup, and whose last statement returns the",
      "JSX that is its template:",
      "",
      "```tsx",
      "export default function Greeting() {",
      "  return <p>Hello, world!</p>;",
      "}",
      "```",
      "",
      "The compiler reports a component without a name (`export default function () { … }`), a",
      "generator, and one whose last statement does not return JSX.",
      "",
      "It also reports an exported function that returns JSX, as a component does, under a name",
      "that is not PascalCase in ASCII letters and digits (`[A-Z][A-Za-z0-9]*`). JSX reads a tag",
      "that starts with a lower-case letter (`<card>`) as an HTML element, and every target names",
      "files after the component (`Card.vue`, and `card.ts` on Angular, whose selector is",
      "`uf-card`), so its name keeps to the characters every file system and target reads alike.",
      "The fix renames the function where its name is used nowhere else.",
    ].join("\n"),
  },
  {
    code: "UF1103",
    name: "invalid-export-name",
    severity: "error",
    title: "A component is exported under a name that is not an identifier",
    description: [
      "Every target writes a component's exports as code, and consumers import a component by",
      "name to use it as a JSX tag, so its exported name must be an identifier.",
      "",
      "```tsx",
      'export { Card as "my card" }; // rejected',
      "export { Card as MyCard };     // accepted",
      "```",
    ].join("\n"),
  },
  {
    code: "UF1104",
    name: "component-name-collision",
    severity: "error",
    title: "Two components' names differ only in case",
    description: [
      "Each component compiles to a file named after it: `Card.vue`, and `card.ts` on Angular.",
      "Two names that differ only in case give the same Angular file and selector, and files",
      "that overwrite each other on case-insensitive file systems (macOS and Windows).",
      "",
      "Rename one of the components.",
    ].join("\n"),
  },
  {
    code: "UF1201",
    name: "framework-import",
    severity: "error",
    title: "Components are framework-free",
    description: [
      "A `.uf.tsx` component is compiled to every framework, so it cannot import one. The",
      "compiler writes each framework's code for you: hooks in React, refs in Vue, runes in",
      "Svelte, signals in Solid.",
      "",
      "Write the component with the authoring API from `unframework` instead:",
      "",
      "```tsx",
      'import { ref } from "unframework";',
      "",
      "export default function Counter() {",
      "  const count = ref(0);",
      "  // …",
      "}",
      "```",
    ].join("\n"),
  },
  {
    code: "UF3001",
    name: "unknown-element",
    severity: "error",
    title: "The element is not an HTML element",
    description: [
      "Lower-case JSX tags are HTML elements, and the compiler emits them unchanged into every",
      "target. A tag that HTML does not define, an obsolete one (`<center>`, `<marquee>`) or one",
      "in the wrong case (`<dIV>`) would be read differently by each framework: Vue resolves it",
      "as a component, Angular rejects it, and the browser renders an unknown element.",
      "",
      "Use the HTML element; a misspelt case has a fix. Components are PascalCase (`<Card>`).",
    ].join("\n"),
  },
  {
    code: "UF3002",
    name: "reserved-element",
    severity: "error",
    title: "A component cannot render this element",
    description: [
      "Some elements belong to the document or to a framework's template syntax, not to a",
      "component's markup:",
      "",
      "- `<html>`, `<head>` and `<body>` are the document's; the browser drops them inside one.",
      "- `<title>`, `<meta>`, `<link>` and `<base>` describe the document: React moves them into",
      "  the `<head>`, and the other frameworks leave them in place.",
      "- `<script>` and `<style>` hold code the compiler cannot analyse; Vue and Angular drop them.",
      "  A component's styles are a stylesheet it imports.",
      "- `<template>`, `<slot>`, `<component>`, `<transition>` and Angular's `<ng-…>` elements",
      "  are template syntax in one framework or another.",
    ].join("\n"),
  },
  {
    code: "UF3003",
    name: "invalid-nesting",
    severity: "error",
    title: "The browser or a framework would repair this markup",
    description: [
      "The HTML parser repairs some nesting: a `<div>` closes an open `<p>`, a `<tr>` directly in",
      "a `<table>` gets a `<tbody>`, text in a table moves out of it, and a void element such as",
      "`<br>` cannot hold children. Server-rendered HTML then becomes a different tree from the",
      "one a client renderer builds, and Svelte, Vue and React each report it. Svelte's compiler",
      "also drops whitespace on its own inside a `<select>` or a `<datalist>`.",
      "",
      "Write the markup the parser keeps: wrap rows in `<tbody>`, use a `<div>` where a",
      "paragraph would contain blocks, and put options on lines of their own.",
    ].join("\n"),
  },
  {
    code: "UF3004",
    name: "non-canonical-attribute",
    severity: "error",
    title: "The attribute is not written in its canonical form",
    description: [
      "Each attribute has one way to be written (P3):",
      "",
      "- HTML names, in lower case: `class`, `for`, `tabindex`, not `className`, `htmlFor` or",
      "  `tabIndex`.",
      '- A boolean attribute without a value: `disabled`, not `disabled=""` or',
      '  `disabled="disabled"`. Its presence turns it on: `disabled="false"` is still disabled.',
      '- A value for every other attribute: in JSX a bare attribute means the string `"true"`,',
      "  which is only meaningful for ARIA states, `data-*` and true/false attributes.",
      "- Numbers in canonical form (`3`, `0.5`): some renderers set these attributes as DOM",
      "  properties, which rewrites any other spelling.",
      '- No `class` rather than an empty one: Vue renders `class=""`, the others leave it out.',
      "  (Whitespace between class names needs no fix: the compiler writes one space.)",
      "",
      "The fix rewrites the attribute where the rewrite is mechanical.",
    ].join("\n"),
  },
  {
    code: "UF3005",
    name: "reserved-attribute",
    severity: "error",
    title: "The attribute belongs to a framework",
    description: [
      "The attribute is syntax or data of one of the target frameworks, so that framework would",
      "not render it as an attribute:",
      "",
      "- Angular binds `bind-*`, `on-*`, `bindon-*`, `ref-*` and `let-*`, consumes `i18n` and",
      "  reserves `ng*` names.",
      "- `slot` and `is` are template syntax in Svelte, Astro and Vue.",
      "- `children`, `dangerouslySetInnerHTML`, `textContent` and React's `suppress…` props are",
      "  framework props, not attributes; write the content as JSX children.",
      "- `data-hk`, `data-astro-*`, `data-v-*`, `data-qwik-*` and `data-uf-*` are attributes",
      "  that frameworks or the compiler add themselves.",
    ].join("\n"),
  },
  {
    code: "UF3006",
    name: "unknown-attribute",
    severity: "error",
    title: "The attribute is not an attribute of this element",
    description: [
      "Elements take HTML's attributes: the global ones (`id`, `class`, `title`, `hidden`, …),",
      "their own (`href` on `<a>`, `alt` on `<img>`), ARIA's `role` and `aria-*`, and `data-*`.",
      "Frameworks treat other names inconsistently: Vue sets a name that matches a DOM property",
      "as that property, and React and Solid give some names meaning of their own.",
      "",
      "Use the element's attribute, or a `data-*` attribute for your own data.",
    ].join("\n"),
  },
  {
    code: "UF3007",
    name: "duplicate-attribute",
    severity: "error",
    title: "The element has the same attribute twice",
    description: [
      "Attribute names are case-insensitive in HTML, and `className` is `class`. With the same",
      "attribute twice, React keeps the last value, the HTML parser the first, and Vue and Svelte",
      "fail to compile. Keep one.",
    ].join("\n"),
  },
  {
    code: "UF3008",
    name: "unportable-attribute-value",
    severity: "error",
    title: "The targets would render this attribute value differently",
    description: [
      "Some values cannot be rendered the same way on every target, and some hold code or a",
      "document the compiler cannot analyse, which it never copies into an output:",
      "",
      "- `javascript:` URLs run code the compiler cannot analyse, and React blocks them.",
      "  Event handlers are the way to run code.",
      "- `srcdoc` holds an HTML document, scripts included, which the frame runs as the page's",
      "  own origin unless it is sandboxed. A `data:` URL that a frame loads (an `<iframe>`'s or",
      "  an `<embed>`'s `src`, an `<object>`'s `data`) is a document too. Load the document from",
      "  a URL, or write its markup in the component. `data:` images and media, and `blob:` URLs,",
      "  hold no code the page runs, and are accepted.",
      "- An empty `src`, or an empty `href` outside `<a>`: React drops it and warns.",
      '- `hidden="until-found"`: React renders `hidden` as a boolean.',
      "- A number out of range, or not a number, in a numeric attribute (`rows`, `span`,",
      "  `<li value>`): renderers that set the DOM property rewrite or reject it.",
      "- A class name holding whitespace other than ASCII's (a no-break space): Angular splits",
      "  class names there, and the other targets keep it in the name.",
    ].join("\n"),
  },
  {
    code: "UF3009",
    name: "ambiguous-jsx-text",
    severity: "error",
    title: "JSX implementations read this text differently",
    description: [
      "JSX does not define its text exactly, and its implementations disagree. Babel (which",
      "Vue's and Solid's JSX use) decodes character references first and then trims the lines,",
      "trimming only spaces and tabs. TypeScript, oxc and esbuild trim the raw lines first, also",
      "trimming Unicode whitespace such as a no-break space, and read U+2028 and U+2029 as line",
      "breaks. So `&#32;` at the end of a line, `&#10;`, a tab, or a raw no-break space next to a",
      "line break means one thing to some tools and another to the rest.",
      "",
      "The compiler lowers text only where every implementation agrees. Write such characters",
      "as references (`&nbsp;`), write a space for a tab, and keep a significant space on the",
      "same line as the text it separates. Numeric references the implementations decode",
      "differently (`&#+65;`, a surrogate such as `&#xD83D;`, a number past U+10FFFF) are",
      "reported too, in attribute strings as well.",
    ].join("\n"),
  },
  {
    code: "UF3010",
    name: "unportable-character",
    severity: "error",
    title: "HTML would not keep this character",
    description: [
      "Each target renders the component's markup on the server as HTML, and the browser parses",
      "it, so a static value must hold only characters the HTML parser keeps as they are:",
      "",
      "- a carriage return becomes a line feed (Svelte's compiler converts it too); in a file",
      "  with CRLF line endings, a value written across lines holds one;",
      "- NUL (U+0000) is dropped from text and replaced in attribute values;",
      "- a lone UTF-16 surrogate cannot be encoded in UTF-8;",
      "- the control characters other than whitespace, and the noncharacters, are not allowed",
      "  in an HTML document.",
      "",
      "Remove the character. A carriage return from a line ending has a fix.",
    ].join("\n"),
  },
  {
    code: "UF3011",
    name: "html-only-reference",
    severity: "warning",
    title: "JSX does not decode this HTML character reference",
    description: [
      "JSX decodes only the named character references of XHTML 1.0 (`&amp;`, `&nbsp;`,",
      "`&copy;`), and numeric ones (`&#x2713;`). The names HTML added later (`&check;`,",
      "`&rbrace;`, `&NewLine;`) stay as written: every target renders `&check;` as those seven",
      "characters, where an HTML or Vue template would show ✓.",
      "",
      "Write the numeric reference for the character (the fix, where it changes nothing else),",
      "or `&amp;check;` for the text itself.",
    ].join("\n"),
  },
  {
    code: "UF3012",
    name: "jsx-outside-template",
    severity: "error",
    title: "JSX can only be in a component's template",
    description: [
      "A component's template is the JSX its last statement returns, with the slot functions in",
      "it. The compiler lowers that tree to each target's template, and Vue's, Svelte's and",
      "Angular's templates are not JSX: they have no counterpart for JSX kept in a variable,",
      "returned from a helper, or passed as a prop that is not a slot.",
      "",
      "```tsx",
      "function renderIcon() {",
      '  return <i class="icon" />; // rejected: a helper that returns JSX',
      "}",
      "```",
      "",
      "Inline the JSX where it is used, move it into a slot function, or extract a component.",
    ].join("\n"),
  },
  {
    code: "UF4001",
    name: "unsupported-capability",
    severity: "warning",
    title: "A selected target cannot support a feature the component uses",
    description: [
      "Each target declares, for every feature, whether it supports it natively, emulates it",
      "with an inline helper, or cannot support it. The component uses a feature that a selected",
      "target cannot support; the diagnostic points at its first use, and the message names the",
      "feature and the target's reason. For example, Astro renders on the server only, so event",
      "handlers are inert there.",
      "",
      "A feature can also be a construct one framework renders differently from HTML and the",
      "other targets. Vue's client, for example, selects the first option of a single-selection",
      'list box (`<select size="2">` without `multiple`), where HTML selects none, so Vue',
      "declares `listbox` unsupported, and the diagnostic points at the list box's `size`.",
      "",
      "The severity comes from the target's capability matrix. With `strict: true`, portability",
      "warnings are errors. Remove the feature, or drop the target.",
    ].join("\n"),
  },
  {
    code: "UF8001",
    name: "plugin-failed",
    severity: "error",
    title: "A compiler plugin failed",
    description: [
      "A compiler plugin's `ir` or `output` hook threw, or returned something other than valid IR",
      "or a list of files. Valid IR has the schema's shape and keeps the invariants every target",
      "relies on (`checkInvariants`): component and export names every target can write, HTML",
      "every target renders alike, and no code or document the compiler cannot analyse. The",
      "message points at the first problems by JSON Pointer.",
      "",
      "The compiler reports it instead of crashing, and leaves the plugin's step out: hooks",
      "receive a frozen module and frozen files, so a hook changes them by returning new ones,",
      "and a failed hook leaves nothing behind.",
      "",
      "Fix the plugin, or remove it from the configuration.",
    ].join("\n"),
  },
  {
    code: "UF9001",
    name: "internal-error",
    severity: "error",
    title: "The compiler failed unexpectedly",
    description: [
      "This is a bug in Unframework. Please open an issue with the file that triggered it:",
      "https://github.com/uxfront-com/unframework/issues/new/choose",
    ].join("\n"),
  },
];

/** Every catalogued diagnostic, by code. */
export const catalogue: ReadonlyMap<DiagnosticCode, CatalogueEntry> = new Map(
  entries.map((entry) => [entry.code, entry]),
);

/** Looks up a code's documentation. */
export function lookup(code: string): CatalogueEntry | undefined {
  return catalogue.get(code as DiagnosticCode);
}

/** The documentation URL of a code. */
export function docsUrl(code: DiagnosticCode): string {
  return `https://unframework.dev/diagnostics/${code}`;
}
