// Source components that show each shape the Svelte target emits: emit.test.ts pins what it
// prints for them, and toolchain.test.ts runs L3, L4 and L5 over that output.

/** The shapes, by name. */
export type Shape =
  | "destructured"
  | "objectForm"
  | "reservedName"
  | "unread"
  | "multiline"
  | "lists"
  | "bindings"
  | "untyped"
  | "runtimeText"
  | "assignedValues"
  | "svgAndFragment"
  | "state"
  | "watchers"
  | "effects"
  | "listeners"
  | "refs"
  | "objectEvents"
  | "watchEdges"
  | "flagWatchers"
  | "teardown"
  | "effectReturns"
  | "copiedCode"
  | "typedMarkup"
  | "unionEvents";

/** Source by shape. */
export const SHAPES: Readonly<Record<Shape, string>> = {
  /** Copied types, destructured props in source order, defaults, props no expression reads. */
  destructured: [
    'type Tone = "info" | "warn";',
    "",
    "export interface BadgeProps {",
    "  label: string;",
    "  tone?: Tone;",
    "  count?: number;",
    "  hidden?: boolean;",
    "}",
    "",
    'export default function Badge({ tone = "info", label, count, hidden = false }: BadgeProps) {',
    "  return <p class={tone}>{label}</p>;",
    "}",
  ].join("\n"),
  /** The props object under the source's name. */
  objectForm: [
    "interface CardProps {",
    "  title: string;",
    "  subtitle?: string;",
    "}",
    "",
    "export default function Card(p: CardProps) {",
    "  return <h2 title={p.subtitle}>{p.title}</h2>;",
    "}",
  ].join("\n"),
  /** A props object under a name Svelte reserves. */
  reservedName: [
    "export default function Card($: { title: string }) {",
    "  return <h2>{$.title}</h2>;",
    "}",
  ].join("\n"),
  /** Props no expression reads. */
  unread: [
    "export default function Hi({ label }: { label?: string }) {",
    "  return <p>Hi</p>;",
    "}",
  ].join("\n"),
  /** Defaults whose literals run over several lines. */
  multiline: [
    "export default function Poem({",
    "  text = `roses",
    "  are red`,",
    '  note = "a\\',
    '  b",',
    "}: { text?: string; note?: string }) {",
    "  return <pre>{text}{note}</pre>;",
    "}",
  ].join("\n"),
  /** A keyed list whose index no expression reads, and a conditional. */
  lists: [
    "export default function List({",
    "  items,",
    "  empty,",
    "}: {",
    "  items: { id: string; name: string }[];",
    "  empty: string;",
    "}) {",
    "  return (",
    "    <ul>",
    "      {items.map((item, index) => <li key={item.id}>{item.name}</li>)}",
    "      {items.length === 0 ? <li>{empty}</li> : null}",
    "    </ul>",
    "  );",
    "}",
  ].join("\n"),
  /** Bound attributes, every form of class and style, and spreads, one of them optional. */
  bindings: [
    "interface LinkAttrs {",
    "  title?: string;",
    "  class?: string;",
    "}",
    "",
    "interface LinkProps {",
    "  href: string;",
    "  attrs: LinkAttrs;",
    "  extra?: LinkAttrs;",
    "  active: boolean;",
    "  tone?: string;",
    "  gap?: string;",
    "  color?: string;",
    "}",
    "",
    "export default function Link({ href, attrs, extra, active, tone, gap, color }: LinkProps) {",
    "  return (",
    "    <p>",
    '      <a href={href} class={["link", { active }, tone]} style={{ color, marginTop: gap, display: "block" }} {...attrs}>',
    "        a",
    "      </a>",
    '      <a href="/b" class={{ active }} style={{ display: "block", "--gap": gap }} {...extra}>',
    "        b",
    "      </a>",
    '      <b class={tone} title={tone ?? "none"} style={{ display: "block" }}>',
    "        c",
    "      </b>",
    "    </p>",
    "  );",
    "}",
  ].join("\n"),
  /** An attribute Svelte's element types declare on some elements only: written, bound, spread. */
  untyped: [
    'type Toggle = "on" | "off";',
    "",
    "interface Hints {",
    "  autocorrect?: Toggle;",
    "}",
    "",
    "export default function Note({ mode, hints }: { mode?: Toggle; hints: Hints }) {",
    "  return (",
    '    <form aria-label="Note">',
    '      <p autocorrect="off">a</p>',
    "      <input autocorrect={mode} />",
    "      <div {...hints}>b</div>",
    "    </form>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Static text Svelte's server renders through its runtime: `style:` directives, the attributes
   * of an element with a spread and of an `<option>`; and a static style with a run of spaces.
   */
  runtimeText: [
    "export default function Quote({ tone }: { tone: string }) {",
    "  return (",
    "    <div>",
    "      <blockquote style={{ fontFamily: '\"Segoe UI\", serif', content: \"'a  b'\", color: tone }}>",
    "        q",
    "      </blockquote>",
    '      <p autocorrect="off" title=\'Name & "title" <x>\' class="q&r" style=\'content: "&"\'>',
    "        c",
    "      </p>",
    '      <select aria-label="Pick">',
    "        <option value='a & \"b\"'>a</option>",
    "      </select>",
    "      <p style=\"content: 'a  b'; color: red\">p</p>",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Bound values Svelte's `set_value` would skip writing when they equal the element's own,
   * never nullish: the analyser reports one that may be there (UF1002).
   */
  assignedValues: [
    "export default function Steps({",
    "  steps,",
    "  score,",
    "  label,",
    "  mode,",
    "}: {",
    "  steps: string[];",
    "  score: number;",
    "  label: string;",
    "  mode: string;",
    "}) {",
    "  return (",
    "    <form>",
    "      <ol>",
    "        {steps.map((step, index) => (",
    "          <li key={step} value={steps.length - 1 - index}>",
    "            {step}",
    "          </li>",
    "        ))}",
    "      </ol>",
    '      <meter min="0" max="10" value={score} title=\'Score & "rank"\'>',
    "        m",
    "      </meter>",
    '      <progress max="10" value={score}>p</progress>',
    "      <data value={label}>d</data>",
    '      <button type="button" value={label}>',
    "        b",
    "      </button>",
    '      <input type="checkbox" name="c" value={mode} />',
    "    </form>",
    "  );",
    "}",
  ].join("\n"),
  /** A root fragment holding SVG (an empty `<title>` too), a conditional and text. */
  svgAndFragment: [
    "export default function Icon({ r, label }: { r: number; label?: string }) {",
    "  return (",
    "    <>",
    '      <svg viewBox="0 0 2 2">',
    "        <title></title>",
    '        <circle cx="1" cy="1" r={r} />',
    "      </svg>",
    '      {label && <p>{label}</p>}{" "}tail',
    "    </>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * State and derived values (ADR-0046): a prop seeding a primitive state, an array state, an
   * expression and a block getter, a static constant, a setup `let`, a function declaration and an
   * arrow, and events with and without a payload (ADR-0047).
   */
  state: [
    'import { computed, defineEmits, ref } from "unframework";',
    "",
    "export interface StepperProps {",
    "  initial?: number;",
    "  step?: number;",
    "}",
    "",
    "export default function Stepper({ initial = 0, step = 1 }: StepperProps) {",
    "  const emit = defineEmits<{ change: [value: number, changes: number]; cleared: [] }>();",
    "",
    "  const limits = { low: 0, high: 10 };",
    "  const count = ref(initial);",
    "  const history = ref<number[]>([]);",
    "  const doubled = computed(() => count.value * 2);",
    "  const parity = computed(() => {",
    '    if (count.value % 2 === 0) return "even";',
    '    return "odd";',
    "  });",
    "  let changes = 0;",
    "",
    "  function add() {",
    "    count.value += step;",
    "    history.value = [...history.value, count.value];",
    "    changes += 1;",
    '    emit("change", count.value, changes);',
    "  }",
    "",
    "  const reset = () => {",
    "    count.value = limits.low;",
    '    emit("cleared");',
    "  };",
    "",
    "  return (",
    '    <div class="stepper" data-parity={parity.value}>',
    "      <output>{count.value}</output>",
    "      {doubled.value > limits.high ? <span>Big</span> : null}",
    '      <button type="button" onClick={add}>',
    "        +{step}",
    "      </button>",
    '      <button type="button" onClick={reset}>',
    "        Reset",
    "      </button>",
    "      <ol>",
    "        {history.value.map((value, index) => (",
    "          <li key={index}>{value}</li>",
    "        ))}",
    "      </ol>",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Watchers (ADR-0048): a ref source with a previous value and a cleanup, a getter through a
   * derived value, an array of refs destructured and annotated as a mutable tuple, as Vue types
   * it, `flush: "post"`, and an immediate prop getter.
   */
  watchers: [
    'import { defineEmits, ref, watch } from "unframework";',
    "",
    "export default function Pager({ size }: { size: number }) {",
    "  const emit = defineEmits<{",
    "    turn: [value: number, previous: number];",
    "    left: [page: number];",
    "    span: [value: number];",
    "    range: [low: number, high: number];",
    "    resize: [value: number, previous?: number];",
    "  }>();",
    "",
    "  const page = ref(1);",
    "  const low = ref(0);",
    "  const high = ref(10);",
    "",
    "  watch(page, (value, previous, onCleanup) => {",
    '    emit("turn", value, previous);',
    "    onCleanup(() => {",
    '      emit("left", value);',
    "    });",
    "  });",
    "",
    "  watch(",
    "    () => high.value - low.value,",
    "    (span) => {",
    '      emit("span", span);',
    "    },",
    "  );",
    "",
    "  watch(",
    "    [low, high],",
    "    ([first, last]: [number, number]) => {",
    '      emit("range", first, last);',
    "    },",
    '    { flush: "post" },',
    "  );",
    "",
    "  watch(",
    "    () => size,",
    "    (value, previous) => {",
    '      emit("resize", value, previous);',
    "    },",
    "    { immediate: true },",
    "  );",
    "",
    "  return (",
    '    <section aria-label="Pager">',
    "      <p>",
    "        Page {page.value}, {low.value} to {high.value} of {size}",
    "      </p>",
    '      <button type="button" onClick={() => page.value++}>',
    "        Next",
    "      </button>",
    "      <button",
    '        type="button"',
    "        onClick={() => {",
    "          low.value += 10;",
    "          high.value += 10;",
    "        }}",
    "      >",
    "        Shift",
    "      </button>",
    "    </section>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Effects and lifecycle hooks (ADR-0048): a `watchEffect` that returns its one cleanup, one
   * that registers it first, `onMounted` reading a template ref and starting a timer held in a
   * setup `let`, and `onUnmounted` clearing it.
   */
  effects: [
    'import { defineEmits, onMounted, onUnmounted, ref, useTemplateRef, watchEffect } from "unframework";',
    "",
    "export default function Ticker({ label }: { label: string }) {",
    "  const emit = defineEmits<{",
    "    title: [text: string];",
    "    released: [text: string];",
    "    ready: [items: number];",
    "    stopped: [];",
    "  }>();",
    "",
    "  const ticks = ref(0);",
    "  const list = useTemplateRef<HTMLUListElement>();",
    "  let timer: ReturnType<typeof setInterval> | undefined;",
    "",
    "  watchEffect((onCleanup) => {",
    "    const text = `${label}: ${ticks.value}`;",
    '    emit("title", text);',
    "    onCleanup(() => {",
    '      emit("released", text);',
    "    });",
    "  });",
    "",
    "  watchEffect((onCleanup) => {",
    "    const text = label;",
    "    onCleanup(() => {",
    '      emit("released", text);',
    "    });",
    '    emit("title", text);',
    "  });",
    "",
    "  onMounted(() => {",
    '    emit("ready", list.value?.childElementCount ?? 0);',
    "    timer = setInterval(() => {",
    "      ticks.value++;",
    "    }, 1000);",
    "  });",
    "",
    "  onUnmounted(() => {",
    "    clearInterval(timer);",
    '    emit("stopped");',
    "  });",
    "",
    "  return (",
    "    <ul ref={list}>",
    "      <li>{label}</li>",
    "      <li>{ticks.value}</li>",
    "    </ul>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Listeners (ADR-0047): capture, `once` and `passive` options, an event Svelte types no
   * attribute for, a non-passive `touchstart`, a plain and a `once` listener of one event on one
   * element, a container's `once` listener around a button that stops the click, and handler
   * parameters annotated with lib.dom's types where Svelte gives another.
   */
  listeners: [
    'import { ref } from "unframework";',
    "",
    "export default function Panel() {",
    "  const log = ref<string[]>([]);",
    '  const draft = ref("");',
    "",
    "  function record(line: string) {",
    "    log.value = [...log.value, line];",
    "  }",
    "",
    "  function updateDraft(event: InputEvent) {",
    "    draft.value = (event.currentTarget as HTMLInputElement).value;",
    "  }",
    "",
    "  function pressed(event: PointerEvent) {",
    "    record(`button ${event.button}`);",
    "  }",
    "",
    "  return (",
    "    <div",
    '      role="presentation"',
    '      onClickCapture={() => record("capture")}',
    '      onClick={() => record("bubble")}',
    "    >",
    '      <button type="button" onClick={pressed} onClickOnce={() => record("once")}>',
    "        Go",
    "      </button>",
    '      <button type="button" onClick={pressed} onTouchstart={() => record("touch")}>',
    "        Touch",
    "      </button>",
    "      <input",
    '        aria-label="Draft"',
    "        onInput={updateDraft}",
    '        onKeydown={(event) => event.key === "Enter" && record(draft.value)}',
    "      />",
    '      <section role="presentation" onClickOnce={() => record("claimed")}>',
    "        <button",
    '          type="button"',
    "          onClick={(event) => {",
    "            event.stopPropagation();",
    '            record("stopped");',
    "          }}",
    "        >",
    "          Stop",
    "        </button>",
    '        <button type="button" onClick={() => record("passed")}>',
    "          Pass",
    "        </button>",
    "      </section>",
    "      <div",
    '        role="presentation"',
    "        onWheelPassive={(event) => record(`wheel ${event.deltaY}`)}",
    '        onAnimationcancel={() => record("cancelled")}',
    "      >",
    '        <p>{log.value.join(", ")}</p>',
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Template refs and ids (ADR-0049): a ref on an element that is always there, one on an element
   * a condition renders, each value kept where the source types it `T | null` (a local, a setup
   * `let`), two ids from one `$props.id()`, and `nextTick`.
   */
  refs: [
    'import { defineEmits, nextTick, ref, useId, useTemplateRef } from "unframework";',
    "",
    "export default function Disclosure() {",
    "  const emit = defineEmits<{ toggled: [items: number] }>();",
    "",
    "  const open = ref(false);",
    "  const field = useTemplateRef<HTMLInputElement>();",
    "  const panel = useTemplateRef<HTMLUListElement>();",
    "  const fieldId = useId();",
    "  const panelId = useId();",
    "  let shown: HTMLUListElement | null = null;",
    "",
    "  async function toggle() {",
    "    open.value = !open.value;",
    "    await nextTick();",
    "    const input: HTMLInputElement | null = field.value;",
    "    input?.focus();",
    "    shown = panel.value;",
    '    emit("toggled", shown?.childElementCount ?? 0);',
    "  }",
    "",
    "  return (",
    '    <section aria-label="Details">',
    "      <label for={fieldId}>Name</label>",
    "      <input id={fieldId} ref={field} />",
    '      <button type="button" aria-controls={panelId} aria-expanded={open.value} onClick={toggle}>',
    "        Toggle",
    "      </button>",
    "      {open.value ? (",
    "        <ul id={panelId} ref={panel}>",
    "          <li>One</li>",
    "          <li>Two</li>",
    "        </ul>",
    "      ) : null}",
    "    </section>",
    "  );",
    "}",
  ].join("\n"),
  /** Events of a component whose props are an object, under a name Svelte reserves. */
  objectEvents: [
    'import { defineEmits } from "unframework";',
    "",
    "interface ChipProps {",
    "  label: string;",
    "}",
    "",
    "export default function Chip($: ChipProps) {",
    "  const emit = defineEmits<{ remove: [label: string] }>();",
    "",
    "  return (",
    '    <button type="button" onClick={() => emit("remove", $.label)}>',
    "      {$.label}",
    "    </button>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Watchers at their edges (ADR-0048): an immediate array source destructured, its values and its
   * previous values annotated as Vue types them, with its previous value `[]` on the first call;
   * a block getter through `$derived.by`, an async callback whose
   * parameters are annotated, and an async `watchEffect` with a cleanup, which reads before its
   * `await` and emits after it.
   */
  watchEdges: [
    'import { defineEmits, nextTick, ref, watch, watchEffect } from "unframework";',
    "",
    "export default function WatchEdges() {",
    "  const emit = defineEmits<{",
    "    pair: [first: number, second: number, previous: number];",
    "    total: [value: number];",
    "    seen: [value: number];",
    "    unseen: [value: number];",
    "  }>();",
    "",
    "  const a = ref(1);",
    "  const b = ref(2);",
    "  const items = ref<number[]>([]);",
    "",
    "  watch(",
    "    [a, b],",
    "    ([first, second]: [number, number], [before]: [number | undefined, number | undefined]) => {",
    '      emit("pair", first, second, before ?? 0);',
    "    },",
    "    { immediate: true },",
    "  );",
    "",
    "  watch(",
    "    () => {",
    "      let sum = 0;",
    "      for (const item of items.value) sum += item;",
    "      return sum;",
    "    },",
    "    async (sum: number, previous: number) => {",
    "      await nextTick();",
    '      emit("total", sum - previous);',
    "    },",
    "  );",
    "",
    "  watchEffect(async (onCleanup) => {",
    "    const first = a.value;",
    '    onCleanup(() => emit("unseen", first));',
    "    await Promise.resolve();",
    '    emit("seen", first);',
    "  });",
    "",
    "  return (",
    "    <button",
    '      type="button"',
    "      onClick={() => {",
    "        a.value++;",
    "        items.value = [...items.value, a.value];",
    "      }}",
    "    >",
    "      {a.value} {b.value} {items.value.length}",
    "    </button>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Watchers of flags: TypeScript narrows `typeof open` at the top of the script to the initial
   * value's type (`false`), where the effect reads `boolean`, so the target queries a source's
   * type inside a function only.
   */
  flagWatchers: [
    'import { defineEmits, ref, watch } from "unframework";',
    "",
    "export default function FlagWatchers() {",
    "  const emit = defineEmits<{",
    "    toggled: [value: boolean, previous?: boolean];",
    "    busy: [text: string];",
    "  }>();",
    "",
    "  const open = ref(false);",
    "  const loading = ref(false);",
    '  const label = ref("Empty");',
    "",
    '  watch(open, (value, previous) => emit("toggled", value, previous), { immediate: true });',
    "  watch([label, loading], ([nextLabel, nextLoading]) => {",
    '    emit("busy", `${nextLabel} ${nextLoading}`);',
    "  });",
    "  watch(",
    "    [label, loading],",
    "    (values, previous) => {",
    '      emit("busy", `${values.join()} ${previous.join()}`);',
    "    },",
    "    { immediate: true },",
    "  );",
    "",
    "  return (",
    '    <button type="button" onClick={() => (open.value = !open.value)}>',
    "      {label.value} {String(loading.value)}",
    "    </button>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Teardown order (ADR-0048): Vue runs every watcher's and `watchEffect`'s cleanup, then the
   * `onUnmounted` hooks in their order, wherever the source declares them.
   */
  teardown: [
    'import { defineEmits, onUnmounted, ref, watch, watchEffect } from "unframework";',
    "",
    "export default function Closing() {",
    "  const emit = defineEmits<{ step: [text: string] }>();",
    "",
    '  const query = ref("");',
    "",
    "  onUnmounted(() => {",
    '    emit("step", "unmounted");',
    "  });",
    "",
    "  watchEffect((onCleanup) => {",
    "    const value = query.value;",
    '    onCleanup(() => emit("step", `effect cleanup ${value}`));',
    "  });",
    "",
    "  watch(",
    "    query,",
    "    (value, previous, onCleanup) => {",
    '      onCleanup(() => emit("step", `watch cleanup ${value}`));',
    "    },",
    "    { immediate: true },",
    "  );",
    "",
    "  onUnmounted(() => {",
    '    emit("step", "closed");',
    "  });",
    "",
    "  return (",
    '    <button type="button" onClick={() => (query.value += "a")}>',
    "      Type",
    "    </button>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * What an effect or a hook returns (ADR-0048): an effect that registers a cleanup and returns
   * early returns its teardown from every way out; a value `watchEffect` or a synchronous
   * `onMounted` returns, which Svelte would take for a teardown, is dropped.
   */
  effectReturns: [
    'import { defineEmits, onMounted, ref, watchEffect } from "unframework";',
    "",
    "export default function EffectReturns({ label }: { label: string }) {",
    "  const emit = defineEmits<{ seen: [text: string]; gone: [text: string] }>();",
    "  const count = ref(0);",
    "  watchEffect((onCleanup) => {",
    "    const text = `${label} ${count.value}`;",
    "    onCleanup(() => {",
    '      emit("gone", text);',
    "    });",
    '    if (text === "") return;',
    '    emit("seen", text);',
    "  });",
    "  watchEffect(() => {",
    "    const name = label;",
    '    if (name === "") {',
    "      return () => {",
    '        emit("gone", name);',
    "      };",
    "    }",
    '    emit("seen", name);',
    "  });",
    "",
    "  onMounted(() => {",
    "    if (count.value > 0) return;",
    "    return () => {",
    '      emit("gone", "mounted");',
    "    };",
    "  });",
    "  return (",
    '    <button type="button" onClick={() => count.value++}>',
    "      {count.value}",
    "    </button>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Copied code a hand scanner would misread (a regular expression holding a quote and a
   * backtick, a multi-line template literal), an async getter-less block of `nextTick`, an untyped
   * template ref, and an object form's events.
   */
  copiedCode: [
    'import { computed, defineEmits, nextTick, onMounted, ref, useTemplateRef } from "unframework";',
    "",
    "export interface Entry {",
    "  id: number;",
    "  name: string;",
    "}",
    "",
    "export default function Misc(props: { entries: Entry[]; title?: string }) {",
    "  const emit = defineEmits<{ picked: [entry: Entry]; ready: [] }>();",
    "  const selected = ref<Entry>();",
    "  const pattern = /[\"'`]/g;",
    "  const count = computed((): number => props.entries.length);",
    "  const box = useTemplateRef();",
    "  let mountedAt: number | undefined;",
    "  const message = `Line one",
    'line two with ${"a"}`;',
    "",
    "  async function pick(entry: Entry) {",
    "    selected.value = entry;",
    "    if (mountedAt === undefined) return;",
    "    await nextTick();",
    '    emit("picked", entry);',
    "  }",
    "",
    "  onMounted(async () => {",
    "    mountedAt = Date.now();",
    "    await nextTick();",
    '    emit("ready");',
    "  });",
    "",
    "  return (",
    '    <section ref={box} aria-label={props.title ?? "Entries"}>',
    '      <p>{message.replace(pattern, "")} {count.value} {selected.value?.name ?? "none"}</p>',
    "      <ul>",
    "        {props.entries.map((entry) => (",
    "          <li key={entry.id}>",
    '            <button type="button" onClick={() => pick(entry)}>',
    "              {entry.name}",
    "            </button>",
    "          </li>",
    "        ))}",
    "      </ul>",
    "    </section>",
    "  );",
    "}",
  ].join("\n"),
  /**
   * Event parameters typed with a union of lib.dom's interfaces (ADR-0047): one whose members
   * Svelte hands it (`onclick`'s `MouseEvent`, `onkeydown`'s `KeyboardEvent` passed on), one that
   * `oninput` reaches, where Svelte hands an `Event`, and an inline handler's.
   */
  unionEvents: [
    'import { defineEmits, ref } from "unframework";',
    "",
    "export default function Choice() {",
    "  const emit = defineEmits<{ activated: [type: string] }>();",
    '  const text = ref("");',
    "",
    "  function activate(event: MouseEvent | KeyboardEvent) {",
    '    emit("activated", event.type);',
    "  }",
    "",
    "  function onKeydown(event: KeyboardEvent) {",
    '    if (event.key === "Enter") activate(event);',
    "  }",
    "",
    "  function edited(event: InputEvent | KeyboardEvent) {",
    "    text.value = (event.currentTarget as HTMLInputElement).value;",
    '    emit("activated", event.type);',
    "  }",
    "",
    "  return (",
    '    <div role="group" aria-label="Choice">',
    '      <div role="button" tabindex="0" onClick={activate} onKeydown={onKeydown}>',
    "        {text.value}",
    "      </div>",
    '      <input aria-label="Text" onInput={edited} onKeyup={edited} />',
    "      <input",
    '        aria-label="Other"',
    '        onInput={(event: InputEvent | KeyboardEvent) => emit("activated", event.type)}',
    "      />",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),
  /** A handler with a cast in a component without a script, which Svelte must parse as TypeScript. */
  typedMarkup: [
    "export default function Plain() {",
    "  return (",
    '    <button type="button" value="a" onClick={(event) => console.log((event.currentTarget as HTMLButtonElement).value)}>',
    "      Log",
    "    </button>",
    "  );",
    "}",
  ].join("\n"),
};
