// The components `renderParityModules` (./render-parity-node.ts) serves to a target's browser
// project, with each suite's cases. That plugin replaces this module with the real list; without
// it, importing this module fails.
import type { ClientSuite } from "./render-parity-client.ts";

export const suites: readonly ClientSuite[] = notServed();

function notServed(): never {
  throw new Error(
    "render-parity-manifest.ts is generated by renderParityModules: run this test in the browser project of a target package's vitest.config.ts.",
  );
}
